[build]
  publish = "."

[[redirects]]
  from = "/rb/profile"
  to = "/.netlify/functions/rbx"
  status = 200
  force = true

[[redirects]]
  from = "/dl/lua"
  to = "/.netlify/functions/dl"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
